account/urls.py
"""Account urls."""


from account import views
from django.contrib.auth import views as auth_views
from django.urls import path

app_name = "account"

urlpatterns = [
    path('my_profile/edit', views.MyProfile.as_view(), name="my_profile"),
    path('my_profile/ava/create/', views.AvaCreateView.as_view(), name='my_profile_ava_create'),
    path('my_profile/ava/list', views.AvaListView.as_view(), name='my_profile_ava_list'),
    path('<int:pk>/my_profile/', views.ShowProfilePageView.as_view(), name="show_profile_page"),

    path('sign-up/', views.SignUpView.as_view(), name='sign_up'),
    path('activate/<str:confirmation_token>', views.ActivateUserView.as_view(), name='activate'),
    path('password/', views.change_password, name='change_password'),
    path('logout/', views.logout, name='user_logout'),
    path('login/', auth_views.LoginView.as_view(template_name="account/user_login.html"), name='user_login'),
]

api/urls.py
"""API urls."""

from rest_framework.routers import DefaultRouter
from .views import BooksAPIViewSet, PostAPIViewSet

from . import views

router = DefaultRouter()
router.register(prefix='posts', viewset=views.PostAPIViewSet, basename='post')
router.register(prefix='books_view', viewset=BooksAPIViewSet, basename='book')

urlpatterns = router.urls

djangoProject/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import include, path
from django.urls import include, path, re_path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

schema_view = get_schema_view(openapi.Info(
    title='Snippets Api',
    default_version='v1',
    description='Description',
    terms_of_service='http://www.google.com/policies/terms/',
    contact=openapi.Contact(email='contact@snippets.local'),
    license=openapi.License(name='BSD License'),

),
    public=True,
    permission_classes=(permissions.AllowAny,)
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('account.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
    re_path(r'^api/v1/swagger/(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0),
            name='schema-json-no-ui'),
    re_path(r'^api/v1/swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    re_path(r'^api/v1/redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-swagger-ui'),
]

main/urls.py
"""Urls of site."""
# from django.contrib import admin
from django.urls import include, path
from django.views.decorators import cache
from django.views.generic import TemplateView

from . import views

urlpatterns = [
    # path('', views.index, name='homepage'),
    path('', TemplateView.as_view(template_name='main/index.html'), name='homepage'),
    # url(r'^favicon\.ico$', RedirectView.as_view(url='/static/images/favicon/favicon.ico')),
    path('about', views.about, name='about'),
    path('posts', views.posts, name='posts'),
    path('post/create', views.post_create, name='post_create'),
    path('posts/update/<int:post_id>', views.post_update, name='post_update'),
    path('posts/<int:post_id>', views.post_show, name='post_show'),
    path('posts/list/', views.PostsListView.as_view(), name='posts_list'),
    #path('posts/all/', cache.cache_page(120)(views.PostsListView.as_view()), name='posts_list'),
    path('posts/list/xlsx', views.DownloadPostsXLSX.as_view(), name='posts_xlsx'),

    path('authors/new', views.authors_new, name='authors_new'),
    # path('authors/all', views.authors_all, name='authors_all'),
    path('authors/all', cache.cache_page(120)(views.authors_all), name='authors_all'),
    path('author/subscribe', views.author_subscribe, name='author_subscribe'),
    path('author/subscribers/all', views.author_subscribers_all, name='author_subscribers_all'),

    path('author/subscribers/notify', views.subscribers_notify, name='subscribers_notify'),

    path('books/all/', views.books, name='books'),
    path('books/list/', views.BooksListView.as_view(), name='books_list'),
    # path('categories/all/', views.categories, name='categories'),
    path('categories/all/', cache.cache_page(120)(views.categories), name='categories'),

    path('posts-page/', TemplateView.as_view(template_name='main/posts_page.html'), name='posts_page'),

    path('contact-us/create/', views.ContactsView.as_view(), name='contact-us-create'),

    path('posts/delete/<int:post_id>/', views.post_delete, name='delete_posts'),
    path('authors/delete/<int:author_id>/', views.author_delete, name='delete_author'),

    path('api/post', views.post_api, name='api_post'),
    path('api/subscribe', views.api_subscribe, name='api_subscribe'),
    path('api/authors/new', views.api_authors_new, name='api_authors_new'),
    path('api/v1/', include('api.urls')),
]

main/models.py
"""Models for site."""
from datetime import datetime

from django.core.cache import cache
from django.db import models
from django.utils.timezone import now


# Create your models here.
class Author(models.Model):
    """Class Author."""

    class Meta:
        """Meta class."""

        db_table = "tbl_users"
        verbose_name = "Author"
        verbose_name_plural = "Authors"
    name = models.CharField("Author name", max_length=100)
    last_name = models.CharField("Author surname", max_length=100, blank=True)
    email = models.EmailField("Email", max_length=50)

    def __str__(self):
        """Print method."""
        return self.name

    def get_full_name(self):
        """Make full name."""
        return f'{self.name} {self.last_name}'

    @property
    def full_name(self):
        """Print full name."""
        return f'{self.name} {self.last_name}'

    def save(self, **kwargs):
        """Save method."""
        super().save()
        key = self.__class__.cache_key()
        cache.delete(key)

    def delete(self, **kwargs):
        """Delete method."""
        super().delete()
        key = self.__class__.cache_key()
        cache.delete(key)

    @classmethod
    def cache_key(cls):
        """Save cache key."""
        dt = datetime.today().strftime('%y-%m-%d')
        key = f'{dt}'
        return key


class Subscriber(models.Model):
    """Class Subsriber."""

    class Meta:
        """Meta class."""

        unique_together = ['email_to', 'author_id']
        db_table = "tbl_subscribers"
        verbose_name = "Subscriber"
        verbose_name_plural = "Subsribers"

    email_to = models.EmailField("Email", max_length=100)
    author_id = models.ForeignKey("Author", on_delete=models.CASCADE)

    def __str__(self):
        """Print method."""
        return self.email_to


class Post(models.Model):
    """Class for Post."""

    class Meta:
        """Meta class."""

        db_table = "  tbl_posts"
        verbose_name = "Post"
        verbose_name_plural = "Posts"
    title = models.CharField("Post title", max_length=100)
    description = models.TextField("Post description", max_length=100)
    content = models.TextField("Post content")
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(default=now)

    def __str__(self):
        """Print method."""
        return f"{self.title} {self.description}"

    def save(self, **kwargs):
        """Save method."""
        super().save()
        key = self.__class__.cache_key()
        cache.delete(key)

    @classmethod
    def cache_key(cls):
        """Cache key method."""
        dt = datetime.today().strftime('%Y-%m-%d')
        key = f'{dt}'
        return key


class Logger(models.Model):
    """Logger class."""

    class Meta:
        """Meta class."""

        db_table = "tb_loggers"

    utm = models.CharField("UTM ", max_length=50)
    time_execution = models.CharField("Time execute ", max_length=70)
    created = models.DateTimeField(auto_now_add=True)
    path = models.CharField("Path", max_length=70)
    user_ip = models.CharField("User IP", max_length=20)

    def __str__(self):
        """Print method."""
        return self.utm


class Comments(models.Model):
    """Set comments model in database."""

    class Meta:
        """Special Meta class to define database and post ordering by created."""

        db_table = "tb_comments"
        ordering = ("created",)

    post = models.ForeignKey("Post", related_name="comments", on_delete=models.CASCADE)
    body = models.TextField("Comment")
    subs_id = models.ForeignKey("Subscriber", on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(default=now)
    activate = models.BooleanField(default=True)

    def __str__(self):
        """Set method of printing."""
        return "Comment by {} on {}".format(self.subs_id, self.post)


class Book(models.Model):
    """Class books."""

    title = models.CharField('Title', max_length=60)
    author = models.ForeignKey('Author', models.CASCADE, related_name='books')
    category = models.ForeignKey('Category', models.CASCADE, related_name='books')

    def __str__(self):
        """Print method."""
        return self.title


class Category(models.Model):
    """Class Category."""

    name = models.CharField("Category name: ", max_length=60)

    def __str__(self):
        """Print method."""
        return self.name

    def save(self, **kwargs):
        """Save method."""
        super().save()
        key = self.__class__.cache_key()
        cache.delete(key)

    @classmethod
    def cache_key(cls):
        """Get Cache Key."""
        dt = datetime.today().strftime('%Y-%m-%d')
        key = f'{dt}'
        return key


class Contacts(models.Model):
    """Class Contacts."""

    email_to = models.EmailField('Email to holders', max_length=70)
    topic = models.CharField(max_length=150)
    text = models.TextField()

main/views.py
"""All wiews of site."""
import io
from time import time

from django.http import HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, View
from django_filters.views import FilterView
from faker import Faker
from main.filters import BooksFilter, PostFilter
from main.forms import PostForm, SubscriberForm
from main.models import Author, Book, Category, Contacts, Post, Subscriber
from main.notify_service import notify
from main.post_service import comment_method, post_all, post_find
from main.subscribe_service import subscribe
from main.tasks import notify_on_subscription, notify_subs
import xlsxwriter


def index(request):
    """Homepage."""
    return render(request, "main/index.html", {'title': 'homepage'})


def about(request):
    """About page."""
    return render(request, "main/about.html", {'title': 'about'})


def posts(request):
    """Show all posts."""
    return render(request, "main/posts.html", {'title': "Posts", "posts": post_all()})


def post_create(request):
    """Create posts."""
    errors = ''
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            form.save()
        else:
            errors = "Cannot save the post"
    else:
        form = PostForm()
    context = {
        "form": form,
        "errors": errors
    }
    return render(request, "main/post_create.html", context=context)


def post_update(request, post_id):
    """Update posts."""
    err = ""
    pst = get_object_or_404(Post, pk=post_id)

    if request.method == "POST":
        form = PostForm(instance=pst, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect("posts")
        else:
            err = "Cannot update."
    else:
        form = PostForm(instance=pst)
    context = {
        "form": form,
        "err": err
    }
    return render(request, "main/post_update.html", context=context)


def post_show(request, post_id):
    """Show post by ID."""
    pst = post_find(post_id)
    comment_form, comments = comment_method(pst, request)
    return render(request, "main/post_show.html",
                  {"title": pst.title, "pst": pst, "comments": comments, "comment_form": comment_form})


def post_delete(request, post_id):
    """Post delete."""
    obj = get_object_or_404(Post, pk=post_id)
    if request.method == "POST":
        obj.delete()
        return redirect('posts_all')
    context = {
        "post": obj
    }
    return render(request, 'main/posts_delete.html', context=context)


def post_api(request):
    """Post api show."""
    posts = post_all()
    data = [dict(title=post.title, description=post.description, content=post.content) for post in posts]
    return JsonResponse(data, safe=False)


def subscribe_notify(author_id, email_to):
    """Subscribe and Notify."""
    if subscribe(author_id, email_to):
        notify(email_to)
        return True
    return False


def author_subscribe(request):
    """Subscribe on Author."""
    errors = ''
    sub_success = False
    email_to = request.POST.get('email_to')
    if request.method == "POST":
        form = SubscriberForm(request.POST)
        if form.is_valid():
            form.save()
            sub_success = True
        else:
            errors = form.errors
    else:
        form = SubscriberForm()

    if sub_success:
        notify_on_subscription.delay(email_to)
        return redirect("author_subscribers_all")

    context = {"form": form, "errors": errors}
    return render(request, "main/subscriber.html", context=context)


def authors_new(request):
    """Generate author."""
    fake = Faker()
    Author(name=fake.name(), email=fake.email()).save()
    return redirect("authors_all")


def author_delete(request, author_id):
    """Delete author."""
    obj = get_object_or_404(Author, pk=author_id)
    if request.method == "POST":
        obj.delete()
        return redirect('authors_all')
    context = {
        "author": obj
    }
    return render(request, 'main/delete_author.html', context=context)


def author_subscribers_all(request):
    """Show all subscribers."""
    allsubs = Subscriber.objects.all()
    return render(request, "main/subscribers_all.html", {"title": "All Subscrivers", "subscribers_all": allsubs})


def books(request):
    """Route to Books."""
    all_books = Book.objects.all().select_related('author', 'category')
    return render(request, 'main/books.html', {'title': 'Books', 'books': all_books})


def categories(request):
    """Route to Categories."""
    all_categories = Category.objects.only('name').distinct().prefetch_related('books')
    return render(request, 'main/categories.html', {'title': 'Categories', 'categories': all_categories})


def authors_all(request):
    """Show a list of authors."""
    allauthors = Author.objects.all()
    return render(request, "main/authors_all.html", {"title": "Authors", "authors": allauthors})


class PostsListView(FilterView):
    """Show post list."""

    paginate_by = 10
    template_name = 'main/posts_list.html'
    filterset_class = PostFilter

    def get_queryset(self):
        queryset = Post.objects.all()
        return queryset

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["get_params"] = '&'.join(f"{key}={val}" for key, val in self.request.GET.items() if key != "page")
        context["cnt"] = context['object_list'].count()
        context["title"] = "All posts"
        return context

class ContactsView(CreateView):
    """Contact view window."""

    success_url = reverse_lazy("home_page")
    model = Contacts
    fields = ("email_to", "topic", "text")


class AuthorsListView2(ListView):
    """Show list of posts ."""

    model = Author
    template_name = 'main/author_list_js.html'

class BooksListView(FilterView):
    paginate_by = 10
    template_name = 'main/books_filter.html'
    filterset_class = BooksFilter

    def get_queryset(self):
        queryset = Book.objects.all().only("title", "category").select_related("category")
        return queryset

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["get_params"] = '&'.join(f"{key}={val}" for key, val in self.request.GET.items() if key != "page")
        context["cnt"] = context['object_list'].count()
        context["title"] = "All books"
        return context


class DownloadPostsXLSX(View):
    """Donwload posts in xlsx."""

    def get(self, request):
        """Get method."""
        output = io.BytesIO()
        wb = xlsxwriter.Workbook(output)
        ws = wb.add_worksheet()
        all_p = Post.objects.all()
        counter = 0
        for p in all_p:
            counter = counter + 1
            ws.write(counter, 0, p.title)
        wb.close()
        output.seek(0)

        f_name = 'Posts.xlsx'
        response = HttpResponse(
            output,
            content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
        )
        response['Content-Disposition'] = 'attachment; filename=%s' % f_name

        return response


def subscribers_notify(request):
    """Notify all subscribers."""
    st = time()
    notify_subs.delay()
    exc_t = time() - st
    print('Time of execution:', exc_t)
    return redirect('homepage')


def api_subscribe(request):
    """Route Subscribers API."""
    author_id = request.GET["author_id"]
    email_to = request.GET["email_to "]
    get_object_or_404(Author, pk=author_id)
    subscribe_notify(author_id, email_to)
    data = {"author_id": author_id}
    return JsonResponse(data, safe=False)


def api_authors_new(request):
    """Generate fake author by Faker for API in Json Format."""
    fake = Faker()
    Author(name=fake.name(), email=fake.email()).save()
    authors = Author.objects.all().values("name", "email")
    return JsonResponse(list(authors), safe=False)

main/templates/main/author_delete.html
{% extends "main/base.html" %}

{% block title %}{{ title }}{% endblock %}


{% block  content %}

    <div class="select2-container"></div>
        <h1>Delete Author</h1>
    <h3>{{ author.name }} will be deleted</h3>
        <div class="payload">
            <form method="post">
                {% csrf_token %}
                <strong>Are you sure about this?</strong>
                <br>
                <br>
                <button class="btn btn-danger">Delete</button>
            </form>
        </div>

{% endblock %}

main/templates/main/authors_all.html
{% extends "main/base.html" %}

{% block title %}{{ title }}{% endblock %}
{% block  content %}
    <div class="container">
        <h1>{{ title }}</h1>
        <div class="payload">
        <table class="table table-hover table-sm">
            <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Name</th>
                <th scope="col">Last name</th>
                <th scope="col">Email</th>
                <th scope="col">Total amount of books</th>
                {% if request.user.is_authenticated %}
                <th scope="col">Delete</th>
                {% endif %}
            </tr>
            </thead>
            <tbody>
            {% for author in authors %}
            <tr>
                <td>{{ author.id }}</td>
                <td>{{ author.name }}</td>
                <td>{{ author.last_name }}</td>
                <td>{{ author.email }}</td>
                <td>{{ author.books.count }}</td>
                <td>{% if request.user.is_authenticated %}
                <a href="{% url 'delete_author' author_id=author.id %}"><button class="btn btn-xs btn-danger">X</button></a>
                {% endif %}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>

        </div>
    </div>
{% endblock %}

main/templates/main/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/assets/main.css">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<nav class="nav justify-content-between bg-success">
    <a class="p-4 text-black-50 link-light" href="{% url "homepage" %}">Homepage</a>
    <a class="p-4 text-black-50 link-light" href="{% url "posts_list" %}">Post List</a>
    <a class="p-4 text-black-50 link-light" href="{% url "posts" %}">Posts</a>
    <a class="p-4 text-black-50 link-light" href="{% url "post_create" %}">Posts create</a>
    <a class="p-4 text-black-50 link-light" href="{% url "authors_all" %}">Authors</a>
    <a class="p-4 text-black-50 link-light" href="{% url "author_subscribers_all" %}">All Subscribers</a>
    <a class="p-4 text-black-50 link-light" href="{% url "subscribers_notify" %}">Email Subscribers</a>
    <a class="p-4 text-black-50 link-light" href="{% url "books" %}">All Books</a>
    <a class="p-4 text-black-50 link-light" href="{% url "categories" %}">All Categories</a>
    <a class="p-4 text-black-50  link-light" href="{% url "posts_xlsx" %}">Download Posts</a>
    {% if request.user.is_authenticated %}
        <a class="p-4 text-black-50 link-light" href="{% url "account:my_profile" %}">Account</a>
        <a class="p-4 text-black-50 link-light" href="{% url "account:my_profile_ava_create" %}">Avatar</a>
        <a class="p-4 text-black-50 link-light" href="{% url "account:change_password" %}">Change password</a>
        <a class="p-4 text-black-50 link-light" href="{% url "account:user_logout" %}">Log out</a>

     {% else %}
        <a class="p-4 text-black-50 link-light" href="{% url "account:user_login" %}">Log in</a>
        <a class="p-4 text-black-50 link-light" href="{% url "account:sign_up" %}">Sign up</a>
    {% endif %}


</nav>

<div class="content">
  {% block content %}{% endblock %}
</div>

<div class="footer-dark">
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-sm-6 col-md-3 item">
                    <h3>Contact us</h3>
                    <ul>
                        <li class="nav-item"><a class="nav-link" href="{% url 'contact-us-create' %}">Send message</a></li>
                    </ul>
                </div>
                <div class="col-sm-6 col-md-3 item">
                    <h3>About</h3>
                    <ul>
                        <li class="nav-item"><a class="nav-link" href="{% url 'about' %}">About</a></li>
                    </ul>
                </div>
                <div class="col-md-6 item text">
                    <h3>Blog</h3>
                    <p>Blog of authors, their books and posts.</p>
                </div>
            </div>
            <p class="copyright">Copyrights © 2021</p>
        </div>
    </footer>
</div>
<script src="https://cdn.jsdelivr.net/npm/vue@2.6.14/dist/vue.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"></script>
<script src="{% static "js/author-list.js" %}"></script>
</body>
</html>

main/templates/main/books.html
{% extends 'main/base.html' %}

{% block title %}
All books
{% endblock %}

{% block content %}
<div class="container">
    <h1>{{ title }}</h1>
    <div class="payload">
        <table class="table table-hover table-sm">
            <thead>
            <tr>
                <th scope="col">Book ID</th>
                <th scope="col">Book title</th>
                <th scope="col">Book category</th>
            </tr>
            </thead>
            <tbody>
            {% for book in books %}
            <tr>
                <td>{{ book.id }}</td>
                <td>{{ book.title }}</td>
                <td>{{ book.category.name}}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

main/templates/main/books_filter.html
{% extends 'main/base.html' %}

{% block title %}
All books
{% endblock %}

{% block content %}
<div class="container">
    <h1>{{ title }}</h1>
    <div class="payload">
                    <div class="mb-1">Count: {{ cnt }}</div>
            <form method="GET">
                {{ filter.form.as_p }}
                <button type="submit" class="btn btn-primary">
                    <span class="glyphicon glyphicon-search"></span>Search
                </button>
            </form>
            <br>
            <hr>
        <table class="table table-hover table-sm">
            <thead>
            <tr>
                <th scope="col">Book ID</th>
                <th scope="col">Title</th>
                <th scope="col">Category</th>
            </tr>
            </thead>
            <tbody>
            {% for book in books_list %}
            <tr>
                <td>{{ book.id }}</td>
                <td>{{ book.title }}</td>
                <td>{{ book.category.name}}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
            <nav aria-label="Page navigation example">
            <ul class="pagination">
                <li class="page-item">
                    {% if is_paginated %}
                        <ul class="pagination">
                            {% if page_obj.has_previous %}
                                <li><a class="page-link" href="?page={{ page_obj.previous_page_number }}{{ get_params }}">&laquo;</a></li>
                            {% else %}
                                <li class="page-item active">
                                     <span class="sr-only">&laquo;</span></a>
                                    </li>
                            {% endif %}
                            {% for i in paginator.page_range %}
                                {% if page_obj.number == i %}
                                    <li class="page-item active">
                                        <a class="page-link" href={{ i }}>{{ i }}<span class="sr-only">(current)</span></a>
                                    </li>
                                {% else %}
                                    <li><a class="page-link" href="?page={{ i }}{{ get_params }}">{{ i }}</a></li>
                                {% endif %}
                            {% endfor %}
                            {% if page_obj.has_next %}
                                <li><a class="page-link" href="?page={{ page_obj.next_page_number }}{{ get_params }}">&raquo;</a></li>
                            {% else %}
                                <li class="page-item active">
                                     <span class="sr-only">&raquo;</span></a>
                                    </li>
                            {% endif %}
                        </ul>
                    {% endif %}
                </li>
            </ul>
        </nav>
    </div>
</div>
{% endblock %}

main/templates/main/contacts_form.html
{% extends "main/base.html" %}

{% block  content %}
<form action="{% url 'contact-us-create' %}" method="POST">
  {% csrf_token %}
  {{form.as_p}}

  <button class="btn btn-lg btn-success">Send</button>

  </form>
{% endblock %}

main/templates/main/index.html
{% extends 'main/base.html' %}
{% block title %} Main Page {% endblock %}
{% block content %}
    <h1>Main page</h1>
    <p>Content Homepage</p>
    <div class="container"></div>
{% endblock %}

main/templates/main/post_show.html
{% extends "main/base.html" %}

{% block title %}{{ title }}{% endblock %}
{% block  content %}
    {% load static %}
    <div class="select2-container"></div>
        <h1>{{ title }}</h1>
        <div class="payload">
            <ul>
                <span class="grey summary">{{ pst.description }}</span>
                    <div class="list-group">
                          <a href="{%  url "post_update" post_id=pst.id %}" class="list-group-item list-group-item-action flex-column align-items-start">
                            {{ pst.content }}</a>
                    {% if request.user.is_authenticated %}
                    <a href="{% url 'delete_posts' post_id=pst.id %}">Delete</a>
                    {% endif %}
                              {% with comments.count as total_comments %}
                                  <br>
                                    <h2>
                                        {{ total_comments }} Comments
                                    </h2>
                              {% endwith %}
                              {% for comment in comments %}
                                <div class="comment">
                                    <p class="info">
                                        Comment {{ forloop.counter }} from {{ comment.subs_id }}
                                        {{ comment.created }}
                                    </p>
                                    {{ comment.body|linebreaks }}
                                </div>
                              {% empty %}
                                <p>Without comments.</p>
                              {% endfor %}
                              {% if new_comment %}
                                <h2>Comment added.</h2>
                              {% else %}
                                <h2>Added new comment</h2>
                                <form method="POST">
                                    {% csrf_token %}
                                    {{comment_form.subs_id}}
                                    <br>
                                    {{ comment_form.body  }}

                                    <br><br>
                                    <button class="btn btn-success">Save</button>

                                </form>
                              {% endif %}
                    </div>

            </ul>
        </div>
{% endblock %}

main/templates/main/post_update.html
{% extends "main/base.html" %}

{% block title %}{{ title }}{% endblock %}


{% block  content %}

    <div class="select2-container"></div>
        <h1>Update post</h1>
        <div class="error">
        <h4 class="error">{{ err }}</h4>
            <div class="dj_error">
                {{ form.errors }}
            </div>


        </div>

        <div class="payload">

            <form method="post">
                {% csrf_token %}

                {{ form.title }}
                <br>
                {{ form.description }}
                <br>
                {{ form.content }}
                <br><br>

                <button class="btn btn-success">Save</button>
            </form>
        </div>

{% endblock %}

main/templates/main/posts_delete.html
{% extends 'main/base.html' %}

{% block title %}
Delete this post
{% endblock %}

{% block content %}
<div class="container">
    <form method="POST">
      {% csrf_token %}
      <h1>You want to delete?</h1>
      <br>
      <button class="btn btn-lg btn-danger">Delete</button>
    </form>
</div>
{% endblock %}

main/templates/main/posts_list.html
{% extends 'main/base.html' %}

{% block title %}Posts{% endblock %}


{% block content %}
<div class="container">
    <h1>{{ title }}</h1>
    <div class="payload">
        <ul>
            {% for post in post_list %}
            <h4>
                <a href="{% url 'post_show' post_id=post.id %}">{{ post.title }}</a>
            </h4>
            <li class="row">
                <span class="grey summary">{{ post.description }}</span>
                {{ post.content }}
            </li>
            <hr>

            {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}